### ISSUE TITLE
Destiny 2 LFG Auto Copy Not Working 

### ISSUE THREAD

**Issue by JordaNx147** [bodaay/DestinyLFGJoinInviteCopier#3]
**Describe the bug**
The /join plug in recently stopped working. I think it is because of the update the D2 LFG server did? 

I unchecked any other plug ins I had active to see if there was conflict but it still was not working. 

**To Reproduce**
1. Open any LFG chat in the D2 Server

**Additional context**
Plug In was working perfectly until D2LFG server changed the way they load LFG rooms. Just wanted to long the issue to make sure it is known.

**Comment by bodaay** [comment]
Thank you for logging it in, I've not even noticed since I have not played since long time

I found out the issue, something changed completely recently in the Discord or BetterDiscord, have no idea when

but I'm fixing it and working on it now

**Comment by JordaNx147** [comment]
Thank you so much! The discord server recently changed the way they load
chat rooms so I bet that is what messed it up.

As someone who mainly uses LFG to complete things and get into farming
groups, your plug in has been great.

Thank you!

**Comment by bodaay** [comment]
its fixed, but I think it will take sometime until BD approves it

so just download it from the repo here and place it in the plugins folders

I would really appreciate if you can test it out and get back to me before I close this issue

**Comment by JordaNx147** [comment]
As soon as I see it working I'll let you know! Thank you for sure a quick
reply.

**Comment by JordaNx147** [comment]
Hey!

Sorry for the late response. I misunderstood and thought it had to be approved before I used it. I downloaded version 1.2 and can confirm it is working on my end.

Thank you so much for fixing it so quicky.
________________________________

**Comment by bodaay** [comment]
np, glad its working out for you, I'll keep the issue open for other people until they official update the plugin on BD
