### ISSUE TITLE
Support other languages than english for the copy pasted command

### ISSUE THREAD

**Issue by gskyu** [bodaay/DestinyLFGJoinInviteCopier#4]
**Is your feature request related to a problem? Please describe.**
The plugin is currently only compatible with the english version of the game. When the language of Destiny 2 is set to something else than english, then the copy pasted command cannot be interpreted by it as the verb of the in-game command changes depending on its language setting.

I would like this plugin to be compatible with other Destiny 2 supported languages.

**Describe the solution you'd like**
Instead of generating only one link, we could generate the english link as it is today followed by supported languages ISO 639 codes' links, each separated by a pipe. 

This would give us somehting like : lf2m gm [/join example#0000]() | [es]() | [it]() | [fr]()

**Describe alternatives you've considered**
Making a branch per supported language and update the readme to properly guide users before they download the plugin.

**Additional context**
Supported languages would only be the ones requested as features for this plugin.

**Comment by bodaay** [comment]
TBH I didnt even know that the game support other than english for commands

I like your approach and simple solution

where do I find the join commands for other languages? and I dont assume you would require the parser to be in multiple languages since I have never seen anyone posting other than English

**Comment by gskyu** [comment]
Yeah, I would not have guessed it either if some of my friends were not playing with their native language in-game.

To find the translations of the ``/join`` command for every supported languages you would have to go on each translations of [this page](https://help.bungie.net/hc/en-us/articles/360048719292-Destiny-2-Text-Chat) and check for the verb used instead of ``join`` at the same location, which is : second chapter, third section, first command.

I already looked up the following ones : 
- Spanish : /unirse ;
- Italian : /partecipa ;
- French : /rejoindre ;
- German : /beitreten ;

To be sure, it would have to be checked in game as well I think. We did not check in-game for the translations above.

I do not think there is a need for the parser to be in multiple languages indeed.

**Comment by bodaay** [comment]
its done, look at the included screen shot in the repo. BetterDiscord take sometime until they officialy update the plugin on their website, you can manually replace the javascript code. please test, I did test and even fixed some weird case with regular expression matching

**Comment by gskyu** [comment]
Damn, you did it quickly, thanks a lot. I'm gonna try to test it before the end of the week and inform you of the results. Thanks again !

**Comment by bodaay** [comment]
appreciate your feedback, and if it solves the issue, please mark it as closed

**Comment by gskyu** [comment]
Hey, sorry, didn't have the time to test it last week. My friend tested it, it seems everything works as expected. Closing the issue, thanks again :)
