### ISSUE TITLE
Add ability to select your language / toggle which join code version you need

### ISSUE THREAD

**Issue by dimmujed** [bodaay/DestinyLFGJoinInviteCopier#5]
Would love the ability to either use the options icon to turn off the join codes for other languages or easily select which language I need, because it takes up so much more space now.

**Comment by bodaay** [comment]
This has been implemented exactly as you requested in the latest release, you can manually update the plugin js file to test it out.

**Comment by dimmujed** [comment]
Looks good! Hopefully this gets pushed via update to everyone else eventually.

Thanks for the plugin and the feature!
